-- MySQL Script generated by MySQL Workbench
-- Fri Apr 24 12:43:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coffee_machine_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coffee_machine_db` ;

-- -----------------------------------------------------
-- Schema coffee_machine_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee_machine_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `coffee_machine_db` ;

-- -----------------------------------------------------
-- Table `coffee_machine_db`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`employee` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `role` ENUM('admin', 'employee', 'cleaner', 'technician') NOT NULL DEFAULT 'employee',
  `pin_code` CHAR(4) NOT NULL,
  `is_authorized_cash` TINYINT(1) NOT NULL DEFAULT '0',
  `is_authorized_inventory` TINYINT(1) NOT NULL DEFAULT '0',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_code` (`employee_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`drink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`drink` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`drink` (
  `drink_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`drink_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`purchase` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `drink_id` INT NOT NULL,
  `payment_type` ENUM('cash', 'card') NOT NULL,
  `amount_paid` DECIMAL(10,2) NOT NULL,
  `purchased_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`purchase_id`),
  INDEX `fk_purchase_drink` (`drink_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_drink`
    FOREIGN KEY (`drink_id`)
    REFERENCES `coffee_machine_db`.`drink` (`drink_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`cash_withdrawal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`cash_withdrawal` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`cash_withdrawal` (
  `withdrawal_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  `withdrawn_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`withdrawal_id`),
  INDEX `fk_cash_withdrawal_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_cash_withdrawal_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`cash_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`cash_transaction` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`cash_transaction` (
  `cash_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL DEFAULT NULL,
  `purchase_id` INT NULL DEFAULT NULL,
  `withdrawal_id` INT NULL DEFAULT NULL,
  `transaction_type` ENUM('cash_sale', 'withdrawal', 'change_refill', 'manual_adjustment') NOT NULL,
  `amount_change` DECIMAL(10,2) NOT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `transaction_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cash_transaction_id`),
  UNIQUE INDEX `uq_cash_tx_purchase` (`purchase_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_cash_tx_withdrawal` (`withdrawal_id` ASC) VISIBLE,
  INDEX `fk_cash_tx_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_cash_tx_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cash_tx_purchase`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `coffee_machine_db`.`purchase` (`purchase_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cash_tx_withdrawal`
    FOREIGN KEY (`withdrawal_id`)
    REFERENCES `coffee_machine_db`.`cash_withdrawal` (`withdrawal_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`cleaning_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`cleaning_log` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`cleaning_log` (
  `cleaning_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `cleaned_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cleaning_id`),
  INDEX `fk_cleaning_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_cleaning_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`ingredient` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `minimum_threshold` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`drink_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`drink_ingredient` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`drink_ingredient` (
  `drink_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `amount_required` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`drink_id`, `ingredient_id`),
  INDEX `fk_di_ingredient` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_di_drink`
    FOREIGN KEY (`drink_id`)
    REFERENCES `coffee_machine_db`.`drink` (`drink_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_di_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`machine_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`machine_inventory` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`machine_inventory` (
  `ingredient_id` INT NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ingredient_id`),
  CONSTRAINT `fk_machine_inventory_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`stock_transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`stock_transfer` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`stock_transfer` (
  `transfer_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `transferred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`transfer_id`),
  INDEX `fk_transfer_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`stock_transfer_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`stock_transfer_item` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`stock_transfer_item` (
  `transfer_item_id` INT NOT NULL AUTO_INCREMENT,
  `transfer_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`transfer_item_id`),
  UNIQUE INDEX `uq_transfer_ingredient` (`transfer_id` ASC, `ingredient_id` ASC) VISIBLE,
  INDEX `fk_transfer_item_ingredient` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_item_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transfer_item_transfer`
    FOREIGN KEY (`transfer_id`)
    REFERENCES `coffee_machine_db`.`stock_transfer` (`transfer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`machine_inventory_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`machine_inventory_history` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`machine_inventory_history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `ingredient_id` INT NOT NULL,
  `employee_id` INT NULL DEFAULT NULL,
  `purchase_id` INT NULL DEFAULT NULL,
  `transfer_item_id` INT NULL DEFAULT NULL,
  `event_type` ENUM('purchase_usage', 'transfer_in', 'manual_adjustment', 'waste', 'correction') NOT NULL,
  `change_amount` DECIMAL(10,2) NOT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  `event_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  INDEX `fk_mih_ingredient` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_mih_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_mih_purchase` (`purchase_id` ASC) VISIBLE,
  INDEX `fk_mih_transfer_item` (`transfer_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_mih_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mih_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mih_purchase`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `coffee_machine_db`.`purchase` (`purchase_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mih_transfer_item`
    FOREIGN KEY (`transfer_item_id`)
    REFERENCES `coffee_machine_db`.`stock_transfer_item` (`transfer_item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`remote_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`remote_inventory` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`remote_inventory` (
  `ingredient_id` INT NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ingredient_id`),
  CONSTRAINT `fk_remote_inventory_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `coffee_machine_db`.`remote_inventory_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`remote_inventory_history` ;

CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`remote_inventory_history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `ingredient_id` INT NOT NULL,
  `employee_id` INT NULL DEFAULT NULL,
  `transfer_item_id` INT NULL DEFAULT NULL,
  `event_type` ENUM('purchase_in', 'transfer_out', 'manual_adjustment', 'waste', 'correction') NOT NULL,
  `change_amount` DECIMAL(10,2) NOT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  `event_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  INDEX `fk_rih_ingredient` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_rih_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_rih_transfer_item` (`transfer_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_rih_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `coffee_machine_db`.`employee` (`employee_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rih_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine_db`.`ingredient` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rih_transfer_item`
    FOREIGN KEY (`transfer_item_id`)
    REFERENCES `coffee_machine_db`.`stock_transfer_item` (`transfer_item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `coffee_machine_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `coffee_machine_db`.`v_cash_balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`v_cash_balance` (`current_cash_balance` INT);

-- -----------------------------------------------------
-- Placeholder table for view `coffee_machine_db`.`v_machine_inventory_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`v_machine_inventory_status` (`ingredient_id` INT, `name` INT, `unit` INT, `quantity` INT, `minimum_threshold` INT, `status` INT, `last_updated` INT);

-- -----------------------------------------------------
-- Placeholder table for view `coffee_machine_db`.`v_remote_inventory_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine_db`.`v_remote_inventory_status` (`ingredient_id` INT, `name` INT, `unit` INT, `quantity` INT, `last_updated` INT);

-- -----------------------------------------------------
-- View `coffee_machine_db`.`v_cash_balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`v_cash_balance`;
DROP VIEW IF EXISTS `coffee_machine_db`.`v_cash_balance` ;
USE `coffee_machine_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `coffee_machine_db`.`v_cash_balance` AS select coalesce(sum(`coffee_machine_db`.`cash_transaction`.`amount_change`),0) AS `current_cash_balance` from `coffee_machine_db`.`cash_transaction`;

-- -----------------------------------------------------
-- View `coffee_machine_db`.`v_machine_inventory_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`v_machine_inventory_status`;
DROP VIEW IF EXISTS `coffee_machine_db`.`v_machine_inventory_status` ;
USE `coffee_machine_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `coffee_machine_db`.`v_machine_inventory_status` AS select `i`.`ingredient_id` AS `ingredient_id`,`i`.`name` AS `name`,`i`.`unit` AS `unit`,`mi`.`quantity` AS `quantity`,`i`.`minimum_threshold` AS `minimum_threshold`,(case when (`mi`.`quantity` <= `i`.`minimum_threshold`) then 'LOW' else 'OK' end) AS `status`,`mi`.`last_updated` AS `last_updated` from (`coffee_machine_db`.`ingredient` `i` join `coffee_machine_db`.`machine_inventory` `mi` on((`mi`.`ingredient_id` = `i`.`ingredient_id`)));

-- -----------------------------------------------------
-- View `coffee_machine_db`.`v_remote_inventory_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffee_machine_db`.`v_remote_inventory_status`;
DROP VIEW IF EXISTS `coffee_machine_db`.`v_remote_inventory_status` ;
USE `coffee_machine_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `coffee_machine_db`.`v_remote_inventory_status` AS select `i`.`ingredient_id` AS `ingredient_id`,`i`.`name` AS `name`,`i`.`unit` AS `unit`,`ri`.`quantity` AS `quantity`,`ri`.`last_updated` AS `last_updated` from (`coffee_machine_db`.`ingredient` `i` join `coffee_machine_db`.`remote_inventory` `ri` on((`ri`.`ingredient_id` = `i`.`ingredient_id`)));
USE `coffee_machine_db`;

DELIMITER $$

USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_purchase_apply_inventory` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_purchase_apply_inventory`
AFTER INSERT ON `coffee_machine_db`.`purchase`
FOR EACH ROW
BEGIN
    UPDATE machine_inventory mi
    JOIN drink_ingredient di ON di.ingredient_id = mi.ingredient_id
    SET mi.quantity = mi.quantity - di.amount_required,
        mi.last_updated = CURRENT_TIMESTAMP
    WHERE di.drink_id = NEW.drink_id;

    INSERT INTO machine_inventory_history (
        ingredient_id,
        employee_id,
        purchase_id,
        transfer_item_id,
        event_type,
        change_amount,
        reason,
        event_timestamp
    )
    SELECT di.ingredient_id,
           NULL,
           NEW.purchase_id,
           NULL,
           'purchase_usage',
           -di.amount_required,
           CONCAT('Ingredient consumed for purchase #', NEW.purchase_id),
           NEW.purchased_at
    FROM drink_ingredient di
    WHERE di.drink_id = NEW.drink_id;

    IF NEW.payment_type = 'cash' THEN
        INSERT INTO cash_transaction (
            employee_id,
            purchase_id,
            withdrawal_id,
            transaction_type,
            amount_change,
            note,
            transaction_time
        )
        VALUES (
            NULL,
            NEW.purchase_id,
            NULL,
            'cash_sale',
            NEW.amount_paid,
            CONCAT('Cash sale for purchase #', NEW.purchase_id),
            NEW.purchased_at
        );
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_purchase_validate_inventory` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_purchase_validate_inventory`
BEFORE INSERT ON `coffee_machine_db`.`purchase`
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM drink_ingredient di
        JOIN machine_inventory mi ON mi.ingredient_id = di.ingredient_id
        WHERE di.drink_id = NEW.drink_id
          AND mi.quantity < di.amount_required
    ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Not enough machine inventory to prepare the selected drink';
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_cash_withdrawal_apply` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_cash_withdrawal_apply`
AFTER INSERT ON `coffee_machine_db`.`cash_withdrawal`
FOR EACH ROW
BEGIN
    INSERT INTO cash_transaction (
        employee_id,
        purchase_id,
        withdrawal_id,
        transaction_type,
        amount_change,
        note,
        transaction_time
    )
    VALUES (
        NEW.employee_id,
        NULL,
        NEW.withdrawal_id,
        'withdrawal',
        -NEW.amount,
        COALESCE(NEW.reason, 'Cash withdrawal'),
        NEW.withdrawn_at
    );
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_cash_withdrawal_authorize` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_cash_withdrawal_authorize`
BEFORE INSERT ON `coffee_machine_db`.`cash_withdrawal`
FOR EACH ROW
BEGIN
    DECLARE v_ok BOOLEAN;

    SELECT is_authorized_cash
    INTO v_ok
    FROM employee
    WHERE employee_id = NEW.employee_id
      AND is_active = TRUE;

    IF v_ok IS NULL OR v_ok = FALSE THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Employee is not authorized to withdraw or update cash';
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_cash_withdrawal_validate_balance` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_cash_withdrawal_validate_balance`
BEFORE INSERT ON `coffee_machine_db`.`cash_withdrawal`
FOR EACH ROW
BEGIN
    DECLARE v_balance DECIMAL(10,2);

    SELECT COALESCE(SUM(amount_change), 0) INTO v_balance
    FROM cash_transaction;

    IF v_balance < NEW.amount THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Not enough cash balance for withdrawal';
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_cash_transaction_authorize_manual` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_cash_transaction_authorize_manual`
BEFORE INSERT ON `coffee_machine_db`.`cash_transaction`
FOR EACH ROW
BEGIN
    DECLARE v_ok BOOLEAN;

    IF NEW.transaction_type IN ('change_refill', 'manual_adjustment') THEN
        IF NEW.employee_id IS NULL THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Manual cash updates require an employee_id';
        END IF;

        SELECT is_authorized_cash
        INTO v_ok
        FROM employee
        WHERE employee_id = NEW.employee_id
          AND is_active = TRUE;

        IF v_ok IS NULL OR v_ok = FALSE THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Employee is not authorized to update cash balance';
        END IF;
    END IF;

    IF NEW.transaction_type = 'cash_sale' AND NEW.purchase_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'cash_sale must reference a purchase';
    END IF;

    IF NEW.transaction_type = 'withdrawal' AND NEW.withdrawal_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'withdrawal must reference a cash_withdrawal';
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_stock_transfer_authorize` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_stock_transfer_authorize`
BEFORE INSERT ON `coffee_machine_db`.`stock_transfer`
FOR EACH ROW
BEGIN
    DECLARE v_ok BOOLEAN;

    SELECT is_authorized_inventory
    INTO v_ok
    FROM employee
    WHERE employee_id = NEW.employee_id
      AND is_active = TRUE;

    IF v_ok IS NULL OR v_ok = FALSE THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Employee is not authorized to update inventory or employee is inactive';
    END IF;
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_stock_transfer_item_apply` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_stock_transfer_item_apply`
AFTER INSERT ON `coffee_machine_db`.`stock_transfer_item`
FOR EACH ROW
BEGIN
    DECLARE v_employee_id INT;

    SELECT employee_id INTO v_employee_id
    FROM stock_transfer
    WHERE transfer_id = NEW.transfer_id;

    UPDATE remote_inventory
    SET quantity = quantity - NEW.quantity,
        last_updated = CURRENT_TIMESTAMP
    WHERE ingredient_id = NEW.ingredient_id;

    INSERT INTO remote_inventory_history (
        ingredient_id,
        employee_id,
        transfer_item_id,
        event_type,
        change_amount,
        reason,
        event_timestamp
    )
    VALUES (
        NEW.ingredient_id,
        v_employee_id,
        NEW.transfer_item_id,
        'transfer_out',
        -NEW.quantity,
        'Transferred from remote warehouse to machine inventory',
        CURRENT_TIMESTAMP
    );

    UPDATE machine_inventory
    SET quantity = quantity + NEW.quantity,
        last_updated = CURRENT_TIMESTAMP
    WHERE ingredient_id = NEW.ingredient_id;

    INSERT INTO machine_inventory_history (
        ingredient_id,
        employee_id,
        transfer_item_id,
        event_type,
        change_amount,
        reason,
        event_timestamp
    )
    VALUES (
        NEW.ingredient_id,
        v_employee_id,
        NEW.transfer_item_id,
        'transfer_in',
        NEW.quantity,
        'Transferred from remote warehouse to machine inventory',
        CURRENT_TIMESTAMP
    );
END$$


USE `coffee_machine_db`$$
DROP TRIGGER IF EXISTS `coffee_machine_db`.`trg_stock_transfer_item_validate` $$
USE `coffee_machine_db`$$
CREATE
TRIGGER `coffee_machine_db`.`trg_stock_transfer_item_validate`
BEFORE INSERT ON `coffee_machine_db`.`stock_transfer_item`
FOR EACH ROW
BEGIN
    DECLARE v_remote_qty DECIMAL(10,2);

    SELECT quantity INTO v_remote_qty
    FROM remote_inventory
    WHERE ingredient_id = NEW.ingredient_id;

    IF v_remote_qty IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Ingredient does not exist in remote inventory';
    END IF;

    IF v_remote_qty < NEW.quantity THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Not enough quantity in remote inventory for transfer';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
